import type { AmbulanceRequestStatus } from "./enum";
import type { AmbulanceRequestType } from "./enum";
import type { EmergencyType } from "./enum";
import type { IAmbulanceBid } from "./ambulance-bid.type";
import type { IDriver } from "./driver.type";
import type { IGuestDriver } from "./guest-driver.type";
import type { IOrganization } from "./organization.type";
import type { IPatient } from "./patient.type";
import type { IVehicle } from "./vehicle.type";
import type { SeverityLevel } from "./enum";
import type { TripCancelledBy } from "./enum";

export interface IAmbulanceRequest {
  id: string;
  patientId: string;
  driverId: string | null;
  vehicleId: string | null;
  organizationId: string | null;
  guestDriverId: string | null;
  driverTrackingToken: string | null;
  requestType: AmbulanceRequestType;
  status: AmbulanceRequestStatus;
  emergencyType: EmergencyType;
  severityLevel: SeverityLevel;
  conditionNotes: string | null;
  contactNumber: string;
  pickupLatitude: number;
  pickupLongitude: number;
  pickupAddress: string;
  destinationLatitude: number | null;
  destinationLongitude: number | null;
  destinationAddress: string | null;
  scheduledAt: string | null;
  acceptedBidId: string | null;
  agreedFare: number | null;
  acceptedAt: string | null;
  enRouteAt: string | null;
  arrivedAt: string | null;
  transportingAt: string | null;
  completedAt: string | null;
  cancelledAt: string | null;
  cancelledBy: TripCancelledBy | null;
  cancellationReason: string | null;
  patient: IPatient;
  driver: IDriver | null;
  vehicle: IVehicle | null;
  organization: IOrganization | null;
  guestDriver: IGuestDriver | null;
  acceptedBid: IAmbulanceBid | null;
  bids: IAmbulanceBid[];
  createdAt: string;
  updatedAt: string;
}
