import type { IAppointment } from "./appointment.type";
import type { IClinicalReview } from "./clinical-review.type";
import type { IDoctorAvailability } from "./doctor-availability.type";
import type { IDoctorDailyRoster } from "./doctor-daily-roster.type";
import type { IDoctorDocument } from "./doctor-document.type";
import type { IDoctorPatientChart } from "./doctor-patient-chart.type";
import type { IDoctorPatientVisit } from "./doctor-patient-visit.type";
import type { IDoctorPrefix } from "./doctor-prefix.type";
import type { IDoctorReview } from "./doctor-review.type";
import type { IDoctorSlot } from "./doctor-slot.type";
import type { IDoctorSpecialty } from "./doctor-specialty.type";
import type { IDoctorWallet } from "./doctor-wallet.type";
import type { IDoctorWeeklySchedule } from "./doctor-weekly-schedule.type";
import type { IExperience } from "./experience.type";
import type { IPatientAccess } from "./patient-access.type";
import type { IQueue } from "./queue.type";
import type { IReportVerifier } from "./report-verifier.type";
import type { IUser } from "./user.type";
import type { IVital } from "./vital.type";
import type { IWioDiscussion } from "./wio-discussion.type";
import type { IWioDiscussionComment } from "./wio-discussion-comment.type";
import type { VerificationStatus } from "./enum";

export interface IDoctor {
  id: string;
  userId: string;
  bio: string | null;
  clinicAddress: string | null;
  consultationFee30min: number | null;
  consultationFee60min: number | null;
  sevenDaysFollowUpFee: number | null;
  countries: string[];
  currentWorkingPlace: string | null;
  designation: string | null;
  educations: string[];
  experiences: IExperience[];
  totalExperienceYear: number;
  languages: string[];
  nidNumber: string;
  qualifications: string;
  registrationNumber: string;
  doctorPrefixId: string;
  doctorPrefix: IDoctorPrefix;
  specialties: IDoctorSpecialty[];
  dailyRosters: IDoctorDailyRoster[];
  doctorSlots: IDoctorSlot[];
  weeklySchedules: IDoctorWeeklySchedule[];
  patientAccess: IPatientAccess[];
  clinicalReviews: IClinicalReview[];
  wioDiscussions: IWioDiscussion[];
  wioDiscussionComments: IWioDiscussionComment[];
  appointments: IAppointment[];
  reviews: IDoctorReview[];
  addedVitals: IVital[];
  availability: IDoctorAvailability | null;
  verificationStatus: VerificationStatus;
  verificationNotes: string | null;
  statusUpdatedAt: string | null;
  verifiedByUserId: string | null;
  documents: IDoctorDocument[];
  wallet: IDoctorWallet | null;
  reportVerifier: IReportVerifier | null;
  charts: IDoctorPatientChart[];
  visits: IDoctorPatientVisit[];
  queues: IQueue[];
  user: IUser;
  totalRating?: number;
  averageRating?: number;
  createdAt: string;
  updatedAt: string;
}
