import type { BloodGroup } from "./enum";
import type { IAddress } from "./address.type";
import type { IAmbulanceRequest } from "./ambulance-request.type";
import type { IAppointment } from "./appointment.type";
import type { ICheckup } from "./checkup.type";
import type { IClinicalReview } from "./clinical-review.type";
import type { IConversation } from "./conversation.type";
import type { IDashboardSnapshot } from "./dashboard-snapshot.type";
import type { IDiagnosisRequest } from "./diagnosis-request.type";
import type { IDoctorPatientChart } from "./doctor-patient-chart.type";
import type { IDoctorReview } from "./doctor-review.type";
import type { IEmergencyContact } from "./emergency-contact.type";
import type { IFieldStop } from "./field-stop.type";
import type { IMedication } from "./medication.type";
import type { IMedicationReminderSetting } from "./medication-reminder-setting.type";
import type { IOrder } from "./order.type";
import type { IPatientAccess } from "./patient-access.type";
import type { IPatientWallet } from "./patient-wallet.type";
import type { IPayment } from "./payment.type";
import type { IPrescription } from "./prescription.type";
import type { IQueueEntry } from "./queue-entry.type";
import type { IReport } from "./report.type";
import type { IReportVerificationRequest } from "./report-verification-request.type";
import type { IRiderReview } from "./rider-review.type";
import type { IUser } from "./user.type";
import type { IVital } from "./vital.type";

export interface IPatient {
  id: string;
  userId: string;
  allergies: string[];
  bloodGroup: BloodGroup | null;
  specialNotes: string | null;
  chronicConditions: string[];
  emergencyContact: IEmergencyContact[];
  height: number | null;
  weight: number | null;
  doctorAccessCode: string | null;
  doctorAccessCodeUpdatedAt: string | null;
  dashboardSnapshots: IDashboardSnapshot[];
  patientAccess: IPatientAccess[];
  clinicalReviews: IClinicalReview[];
  user: IUser;
  prescriptions: IPrescription[];
  reports: IReport[];
  checkups: ICheckup[];
  vitals: IVital[];
  reviews: IDoctorReview[];
  conversations: IConversation[];
  payments: IPayment[];
  appointments: IAppointment[];
  medications: IMedication[];
  medicationReminderSetting: IMedicationReminderSetting | null;
  ambulanceRequests: IAmbulanceRequest[];
  reportVerificationRequests: IReportVerificationRequest[];
  wallet: IPatientWallet | null;
  diagnosisRequests: IDiagnosisRequest[];
  fieldStops: IFieldStop[];
  charts: IDoctorPatientChart[];
  queueEntries: IQueueEntry[];
  addresses: IAddress[];
  orders: IOrder[];
  riderReviews: IRiderReview[];
  createdAt: string;
  updatedAt: string;
}
