import type { IDelivery } from "./delivery.type";
import type { IRiderDocument } from "./rider-document.type";
import type { IRiderOrderOffer } from "./rider-order-offer.type";
import type { IRiderReview } from "./rider-review.type";
import type { IRiderVehicle } from "./rider-vehicle.type";
import type { IRiderWallet } from "./rider-wallet.type";
import type { IUser } from "./user.type";
import type { RiderBatch } from "./enum";
import type { RiderStatus } from "./enum";
import type { VerificationStatus } from "./enum";

export interface IRider {
  id: string;
  userId: string;
  status: RiderStatus;
  verificationStatus: VerificationStatus;
  isActive: boolean;
  contactNumber: string | null;
  address: string | null;
  averageRating: number;
  ratingCount: number;
  totalDeliveries: number;
  batch: RiderBatch;
  batchScore: number;
  totalOffersReceived: number;
  totalOffersAccepted: number;
  totalOffersRejected: number;
  totalOffersExpired: number;
  acceptanceRate: number;
  completionRate: number;
  totalOrdersCancelled: number;
  avgDeliveryTimeMin: number;
  onTimeDeliveryRate: number;
  peakHourDeliveries: number;
  batchEvaluatedAt: string | null;
  batchPromotedAt: string | null;
  batchDemotedAt: string | null;
  latitude: string | null;
  longitude: string | null;
  lastLocationUpdate: string | null;
  verificationNotes: string | null;
  verifiedByUserId: string | null;
  statusUpdatedAt: string | null;
  user: IUser;
  vehicles: IRiderVehicle[];
  documents: IRiderDocument[];
  deliveries: IDelivery[];
  reviews: IRiderReview[];
  wallet: IRiderWallet | null;
  orderOffers: IRiderOrderOffer[];
  createdAt: string;
  updatedAt: string;
}
